
name: flutter-macos
env:
    TZ: Asia/Shanghai

on:
  push:
    paths:
      - '.github/workflows/flutter-macos.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: AoEiuV020/FlutterDemo
    - uses: subosito/flutter-action@v1
      with:
          channel: 'stable'
    - run: |
          flutter config --enable-macos-desktop
          flutter pub get
          flutter build macos --release
    - run: find . > fileList.txt
    - name: upload fileList.txt
      uses: actions/upload-artifact@master
      with:
        name: fileList.txt
        path: ./fileList.txt
    - name: zip
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: build/macos/Build/Products/Release
        filename: ${{ github.workspace }}/build/result.zip
    - name: upload artifact result.zip
      uses: actions/upload-artifact@master
      with:
        name: build
        path: build/result.zip

