
name: flutter-ios
env:
    TZ: Asia/Shanghai

on:
  push:
    paths:
      - '.github/workflows/flutter-ios.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        name: [ios]
        include:
        - name: ios
          config: ios
          os: macos-latest
          BUILD_ARGS: "--no-codesign"
          RELEASE_PATH: Payload
          RELEASE_DIRECTORY: build/ios/iphoneos
          POST_COMMAND: |
            cd build/ios/iphoneos
            mkdir Payload
            cd Payload
            ln -s ../Runner.app
      # Disable fail-fast; we want results from all OSes even if one fails.
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      with:
        repository: AoEiuV020/FlutterDemo
    - uses: subosito/flutter-action@v1
      with:
          channel: 'stable'
    - name: enable config (${{ matrix.config }})
      if: "${{ matrix.ENABLE_CONFIG != '' }}"
      run: flutter config --enable-${{ matrix.ENABLE_CONFIG }}
    - run: |
          flutter pub get
          flutter build ${{ matrix.config }} ${{ matrix.BUILD_ARGS }}
    - name: post
      run: ${{ matrix.POST_COMMAND }}
    - name: zip
      if: "${{ matrix.RELEASE_DIRECTORY != '' }}"
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        path: ${{ matrix.RELEASE_PATH }}
        directory: ${{ matrix.RELEASE_DIRECTORY }}
        filename: ${{ github.workspace }}/build/result-${{ matrix.config }}.zip
    - name: Archive Production Artifact
      if: "${{ matrix.RELEASE_PATH != '' }}"
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.config }}-build
        path: build/result-${{ matrix.config }}.zip
