
name: flutter-windows
env:
    TZ: Asia/Shanghai

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: AoEiuV020/FlutterDemo
    - uses: subosito/flutter-action@v1
      with:
          channel: 'stable'
    - run: |
          flutter pub get
          flutter build windows --release
    - run: tree /f > fileList.txt
    - name: upload fileList.txt
      uses: actions/upload-artifact@master
      with:
        name: fileList.txt
        path: ./fileList.txt
    - name: zip
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: build/windows/runner/Release
        filename: ${{ github.workspace }}/build/result.zip
    - name: upload artifact result.zip
      uses: actions/upload-artifact@master
      with:
        name: build
        path: build/result.zip

