name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
    build:
        name: make biuld.zip
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - run: ./build.sh
        - name: upload artifact
          uses: actions/upload-artifact@master
          with:
              name: build
              path: build/output

